---
- hosts: all
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes

  pre_tasks:
    - name: apt-get update
      raw: sudo apt-get update
    # Python is required for ansible
    - name: Install Python 3 & pip
      raw: sudo apt-get -y install python3 python3-pip
    # apt module prefers `apt` instead of `apt-get`
    # or else it issues warnings
    - name: Install aptitude
      raw: sudo apt-get -y install aptitude

  roles:
    - tunnel-server
